# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99c03297930e27a95e2eb0ca833b12cd5e3d3ae530e4e04a88563e9031ad075309e352567a07eafd4c158ed77e5539ae90b1361a2d504bc3405c421a4401be30

test:
  secret_key_base: 9ae76d122a9cf8e9bb7f08fa53b7ecbdb146caeb032639bfaa084e9d594893db90364d9cbadbd2ec40cbb49676e759f37f8669057e06aa489c418e094c730df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
